/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ImprintImport } from './routes/imprint'
import { Route as IndexImport } from './routes/index'
import { Route as AuthGoogleRouteImport } from './routes/auth/google/route'
import { Route as AuthGoogleIndexImport } from './routes/auth/google/index'
import { Route as AuthGoogleMissingScopeImport } from './routes/auth/google/missing-scope'
import { Route as AuthGoogleCallbackImport } from './routes/auth/google/callback'

// Create/Update Routes

const ImprintRoute = ImprintImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthGoogleRouteRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRoute,
} as any)

const AuthGoogleIndexRoute = AuthGoogleIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthGoogleRouteRoute,
} as any)

const AuthGoogleMissingScopeRoute = AuthGoogleMissingScopeImport.update({
  id: '/missing-scope',
  path: '/missing-scope',
  getParentRoute: () => AuthGoogleRouteRoute,
} as any)

const AuthGoogleCallbackRoute = AuthGoogleCallbackImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGoogleRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintImport
      parentRoute: typeof rootRoute
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackImport
      parentRoute: typeof AuthGoogleRouteImport
    }
    '/auth/google/missing-scope': {
      id: '/auth/google/missing-scope'
      path: '/missing-scope'
      fullPath: '/auth/google/missing-scope'
      preLoaderRoute: typeof AuthGoogleMissingScopeImport
      parentRoute: typeof AuthGoogleRouteImport
    }
    '/auth/google/': {
      id: '/auth/google/'
      path: '/'
      fullPath: '/auth/google/'
      preLoaderRoute: typeof AuthGoogleIndexImport
      parentRoute: typeof AuthGoogleRouteImport
    }
  }
}

// Create and export the route tree

interface AuthGoogleRouteRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthGoogleMissingScopeRoute: typeof AuthGoogleMissingScopeRoute
  AuthGoogleIndexRoute: typeof AuthGoogleIndexRoute
}

const AuthGoogleRouteRouteChildren: AuthGoogleRouteRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthGoogleMissingScopeRoute: AuthGoogleMissingScopeRoute,
  AuthGoogleIndexRoute: AuthGoogleIndexRoute,
}

const AuthGoogleRouteRouteWithChildren = AuthGoogleRouteRoute._addFileChildren(
  AuthGoogleRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/auth/google': typeof AuthGoogleRouteRouteWithChildren
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/missing-scope': typeof AuthGoogleMissingScopeRoute
  '/auth/google/': typeof AuthGoogleIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/missing-scope': typeof AuthGoogleMissingScopeRoute
  '/auth/google': typeof AuthGoogleIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/auth/google': typeof AuthGoogleRouteRouteWithChildren
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/google/missing-scope': typeof AuthGoogleMissingScopeRoute
  '/auth/google/': typeof AuthGoogleIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imprint'
    | '/auth/google'
    | '/auth/google/callback'
    | '/auth/google/missing-scope'
    | '/auth/google/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imprint'
    | '/auth/google/callback'
    | '/auth/google/missing-scope'
    | '/auth/google'
  id:
    | '__root__'
    | '/'
    | '/imprint'
    | '/auth/google'
    | '/auth/google/callback'
    | '/auth/google/missing-scope'
    | '/auth/google/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImprintRoute: typeof ImprintRoute
  AuthGoogleRouteRoute: typeof AuthGoogleRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImprintRoute: ImprintRoute,
  AuthGoogleRouteRoute: AuthGoogleRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/imprint",
        "/auth/google"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/imprint": {
      "filePath": "imprint.tsx"
    },
    "/auth/google": {
      "filePath": "auth/google/route.tsx",
      "children": [
        "/auth/google/callback",
        "/auth/google/missing-scope",
        "/auth/google/"
      ]
    },
    "/auth/google/callback": {
      "filePath": "auth/google/callback.tsx",
      "parent": "/auth/google"
    },
    "/auth/google/missing-scope": {
      "filePath": "auth/google/missing-scope.tsx",
      "parent": "/auth/google"
    },
    "/auth/google/": {
      "filePath": "auth/google/index.tsx",
      "parent": "/auth/google"
    }
  }
}
ROUTE_MANIFEST_END */
