/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SetupIndexImport } from './routes/setup/index'
import { Route as SetupCustomImport } from './routes/setup/custom'
import { Route as SetupCompleteImport } from './routes/setup/complete'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SetupIndexRoute = SetupIndexImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRoute,
} as any)

const SetupCustomRoute = SetupCustomImport.update({
  id: '/setup/custom',
  path: '/setup/custom',
  getParentRoute: () => rootRoute,
} as any)

const SetupCompleteRoute = SetupCompleteImport.update({
  id: '/setup/complete',
  path: '/setup/complete',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/setup/complete': {
      id: '/setup/complete'
      path: '/setup/complete'
      fullPath: '/setup/complete'
      preLoaderRoute: typeof SetupCompleteImport
      parentRoute: typeof rootRoute
    }
    '/setup/custom': {
      id: '/setup/custom'
      path: '/setup/custom'
      fullPath: '/setup/custom'
      preLoaderRoute: typeof SetupCustomImport
      parentRoute: typeof rootRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/custom': typeof SetupCustomRoute
  '/setup': typeof SetupIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/custom': typeof SetupCustomRoute
  '/setup': typeof SetupIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/custom': typeof SetupCustomRoute
  '/setup/': typeof SetupIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/setup/complete' | '/setup/custom' | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/setup/complete' | '/setup/custom' | '/setup'
  id: '__root__' | '/' | '/setup/complete' | '/setup/custom' | '/setup/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetupCompleteRoute: typeof SetupCompleteRoute
  SetupCustomRoute: typeof SetupCustomRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetupCompleteRoute: SetupCompleteRoute,
  SetupCustomRoute: SetupCustomRoute,
  SetupIndexRoute: SetupIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/setup/complete",
        "/setup/custom",
        "/setup/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/setup/complete": {
      "filePath": "setup/complete.tsx"
    },
    "/setup/custom": {
      "filePath": "setup/custom.tsx"
    },
    "/setup/": {
      "filePath": "setup/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
